# Data-X Fall 2018: Homework 06 

### Machine Learning

**Authors:** Sana Iqbal (Part 1, 2, 3)


In this homework, you will do some exercises with prediction. Please note that not all tests are visible. There will be further tests on gradescope. 


In [144]:
import numpy as np
import pandas as pd
import otter 

In [145]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
#import xgboost as xgb

In [146]:
grader = otter.Notebook()

## Part 1



#### 1.a Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [147]:
#Read data & print it
data = pd.read_csv("diabetesdata.csv")
print(data)

     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
0                6         148.0  72        0  33.6     0.627  50.0   
1                1           NaN  66        0  26.6     0.351  31.0   
2                8         183.0  64        0  23.3     0.672   NaN   
3                1           NaN  66       94  28.1     0.167  21.0   
4                0         137.0  40      168  43.1     2.288  33.0   
..             ...           ...  ..      ...   ...       ...   ...   
763             10         101.0  76      180  32.9     0.171  63.0   
764              2         122.0  70        0  36.8     0.340  27.0   
765              5         121.0  72      112  26.2     0.245  30.0   
766              1         126.0  60        0  30.1     0.349  47.0   
767              1          93.0  70        0  30.4     0.315  23.0   

     IsDiabetic  
0             1  
1             0  
2             1  
3             0  
4             1  
..          ...  
763           0  
764

In [148]:
grader.check('q1a')

All tests passed!

#### 1.b Calculate the percentage of NaN values in each column.

In [149]:
# NullsPerColumn should be a dataframe that includes a column called 'Percentage Null'. The values are between 0 and 1.
NullsPerColumn = data.isnull().sum() / len(data)
NullsPerColumn = pd.DataFrame(NullsPerColumn).rename(columns= {0: "Percentage Null"})
NullsPerColumn

Percentage Null
TimesPregnant         0.000000
glucoseLevel          0.044271
BP                    0.000000
insulin               0.000000
BMI                   0.000000
Pedigree              0.000000
Age                   0.042969
IsDiabetic            0.000000

In [150]:
grader.check('q1b')

All tests passed!

**1.c Calculate the TOTAL percent of ROWS with NaN values in the dataframe (make sure values are floats).**

In [151]:
# Return values between 0 and 1. 
PercentNull =  data.isnull().any(axis = 1).sum()/float(len(data))
PercentNull

0.08333333333333333

**1.d Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% test split.**


In [152]:
#split values
from sklearn.model_selection import train_test_split

numTest = round(0.15*len(data),0)
train_df, test_df = data.loc[numTest+1:,:], data.loc[:numTest,:]

**1.e Replace the Nan values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature.**

In [153]:
train_df = train_df.apply(lambda x: x.fillna(x.mean()),axis=0)

In [154]:
train_df.isna().sum()

TimesPregnant    0
glucoseLevel     0
BP               0
insulin          0
BMI              0
Pedigree         0
Age              0
IsDiabetic       0
dtype: int64

In [155]:
train_df = train_df.apply(lambda x: x.fillna(x.mean()),axis=0)
test_df = test_df.apply(lambda x: x.fillna(x.mean()),axis=0)

#train_test_split(data.loc[:,"TimesPregnant":"Age"], data["IsDiabetic"], test_size = 0.15)

In [156]:
grader.check('q1e')

All tests passed!

**1.f Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [157]:
X_train = train_df.loc[:,'TimesPregnant':'Age']
Y_train = train_df.loc[:,'IsDiabetic']
X_test  = test_df.loc[:,'TimesPregnant':'Age']
Y_test = test_df.loc[:,'IsDiabetic']

[X_train.shape, Y_train.shape, X_test.shape,Y_test.shape]

[(652, 7), (652,), (116, 7), (116,)]

In [158]:
grader.check('q1f')

All tests passed!

**1.g Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies.**

In [159]:
# Logistic Regression

logreg = LogisticRegression(solver = "newton-cg", multi_class = 'ovr')  # use newton-cg solver and 'ovr' for multi_class
logreg.fit(X_train, Y_train)
logreg_train_acc = logreg.score(X_train, Y_train)
logreg_test_acc = logreg.score(X_test, Y_test)
print ('logreg training acuracy= ',logreg_train_acc)
print('logreg test accuracy= ',logreg_test_acc)

logreg training acuracy=  0.7806748466257669
logreg test accuracy=  0.7672413793103449


In [160]:
# Perceptron

perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
perceptron_train_acc = perceptron.score(X_train, Y_train)
perceptron_test_acc = perceptron.score(X_test, Y_test)
print ('perceptron training acuracy= ',perceptron_train_acc)
print('perceptron test accuracy= ',perceptron_test_acc)

perceptron training acuracy=  0.6809815950920245
perceptron test accuracy=  0.603448275862069


In [161]:
# Adaboost
adaboost = AdaBoostClassifier()
adaboost.fit(X_train, Y_train)
adaboost_train_acc = adaboost.score(X_train, Y_train)
adaboost_test_acc = adaboost.score(X_test, Y_test)
print ('adaboost training acuracy= ',adaboost_train_acc)
print('adaboost test accuracy= ',adaboost_test_acc)

adaboost training acuracy=  0.8174846625766872
adaboost test accuracy=  0.75


In [162]:
# Random Forest

random_forest = RandomForestClassifier()
random_forest.fit(X_train, Y_train)
random_forest_train_acc = random_forest.score(X_train, Y_train)
random_forest_test_acc = random_forest.score(X_test, Y_test)
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)

C:\Users\Chad\.conda\envs\data-x\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


random_forest training acuracy=  0.9861963190184049
random_forest test accuracy=  0.7241379310344828


**1.h Is mean imputation is the best type of imputation to use? Why or why not? What are some other ways to impute the data?**

In [163]:
better = False # [boolean] change this to be True if you believe mean imputation is the best imputation to use, and False otherwise
explanation = "The best type of imputation to use depends on the distribution of the feature. If the data appears normally distributed, then using the mean would be a good choice. However, sometimes it may be best to just remove rows with NaN or replace them with zeros. In other cases it may be better to use the median or some type of algorithm such as KNN." # [string] write why or why not here, and other ways

## Part 2


__2.a Add columns __`BMI_band`__ & __`Pedigree_band`__  to  a new dataframe called __`data2`__  by cutting __`BMI`__ & __`Pedigree`__ into 3 intervals. PRINT the first 5 rows of __`data2`__.


In [164]:
# YOUR CODE HERE

data2 = data.copy()
data2['BMI_band'] = pd.cut(data2['BMI'], bins = 3)
data2['Pedigree_band'] = pd.cut(data2['Pedigree'], bins = 3)
data2.head(5)

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic  \
0              6         148.0  72        0  33.6     0.627  50.0           1   
1              1           NaN  66        0  26.6     0.351  31.0           0   
2              8         183.0  64        0  23.3     0.672   NaN           1   
3              1           NaN  66       94  28.1     0.167  21.0           0   
4              0         137.0  40      168  43.1     2.288  33.0           1   

           BMI_band    Pedigree_band  
0  (22.367, 44.733]  (0.0757, 0.859]  
1  (22.367, 44.733]  (0.0757, 0.859]  
2  (22.367, 44.733]  (0.0757, 0.859]  
3  (22.367, 44.733]  (0.0757, 0.859]  
4  (22.367, 44.733]    (1.639, 2.42]

__2.b Print the category intervals for __`BMI_band`__ & __`Pedigree_band`.

In [165]:
data2['BMI_band'].values.unique()

[(22.367, 44.733], (-0.0671, 22.367], (44.733, 67.1]]
Categories (3, interval[float64]): [(-0.0671, 22.367] < (22.367, 44.733] < (44.733, 67.1]]

In [166]:
data2['Pedigree_band'].values.unique()

[(0.0757, 0.859], (1.639, 2.42], (0.859, 1.639]]
Categories (3, interval[float64]): [(0.0757, 0.859] < (0.859, 1.639] < (1.639, 2.42]]

In [167]:
print('BMI_Band_Interval: ' + "[(22.367, 44.733], (-0.001, 22.367], (44.733, 67.1]]")
print('Pedigree_Band_Interval: ' + '[(0.077, 0.859], (1.639, 2.42], (0.859, 1.639]]')
                                                        

BMI_Band_Interval: [(22.367, 44.733], (-0.001, 22.367], (44.733, 67.1]]
Pedigree_Band_Interval: [(0.077, 0.859], (1.639, 2.42], (0.859, 1.639]]


__2.c Group __`data`__ by __`Pedigree_band`__ & determine ratio of diabetic in each band.__

In [168]:
# YOUR CODE HERE
 
groupedData2 = data2.groupby("Pedigree_band").agg({'IsDiabetic':'sum'})
groupedData2['Count'] = data2.groupby(['Pedigree_band'])['IsDiabetic'].count()

pedigree_DiabeticRatio = pd.DataFrame(groupedData2['IsDiabetic']/ groupedData2['Count'], columns = ['IsDiabetic'])
pedigree_DiabeticRatio

IsDiabetic
Pedigree_band              
(0.0757, 0.859]    0.327007
(0.859, 1.639]     0.540541
(1.639, 2.42]      0.444444

In [169]:

groupedData2 = data2[['IsDiabetic','Pedigree_band']].groupby("Pedigree_band").mean()
groupedData2

IsDiabetic
Pedigree_band              
(0.0757, 0.859]    0.327007
(0.859, 1.639]     0.540541
(1.639, 2.42]      0.444444

__2.d Group  __`data`__ by __`BMI_band`__ & determine ratio of diabetic in each band.__

In [170]:
# YOUR CODE HERE

groupedData2 = data2.groupby("BMI_band").agg({'IsDiabetic':'sum'})
groupedData2['Count'] = data2.groupby(['BMI_band'])['IsDiabetic'].count()

BMI_DiabeticRatio = pd.DataFrame(groupedData2['IsDiabetic']/ groupedData2['Count'], columns = ['IsDiabetic'])
BMI_DiabeticRatio

IsDiabetic
BMI_band                     
(-0.0671, 22.367]    0.039216
(22.367, 44.733]     0.358297
(44.733, 67.1]       0.611111

__2.e Convert these features - 'BP','insulin','BMI' and 'Pedigree'   into categorical values by mapping different bands of values of these features to integers 0,1,2 in a dataframe called `data3`.__  
 
HINT: USE pd.cut with bin=3 to create 3 bins



In [171]:
# YOUR CODE HERE

data3 = data2.copy()
data3['BP'] = pd.cut(data3['BP'], bins = 3, labels = [0,1,2])
data3['insulin'] = pd.cut(data3['insulin'], bins = 3, labels = [0,1,2])
data3['BMI'] = pd.cut(data3['BMI'], bins = 3, labels = [0,1,2])
data3['Pedigree'] = pd.cut(data3['Pedigree'], bins = 3, labels = [0,1,2])
#data3.drop(columns = ['BMI_band','Pedigree_band'], inplace = True)
data3.head()

TimesPregnant  glucoseLevel BP insulin BMI Pedigree   Age  IsDiabetic  \
0              6         148.0  1       0   1        0  50.0           1   
1              1           NaN  1       0   1        0  31.0           0   
2              8         183.0  1       0   1        0   NaN           1   
3              1           NaN  1       0   1        0  21.0           0   
4              0         137.0  0       0   1        2  33.0           1   

           BMI_band    Pedigree_band  
0  (22.367, 44.733]  (0.0757, 0.859]  
1  (22.367, 44.733]  (0.0757, 0.859]  
2  (22.367, 44.733]  (0.0757, 0.859]  
3  (22.367, 44.733]  (0.0757, 0.859]  
4  (22.367, 44.733]    (1.639, 2.42]


__2.f Now consider the original dataset again, instead of generalizing the NAN values with the mean of the feature we will try assigning values to NANs based on some hypothesis. For example for age we assume that the relation between BMI and BP of people is a reflection of the age group. We can have 9 types of BMI and BP relations and our aim is to find the median age of each of that group:__

Your Age guess matrix will look like this:  

| BMI | 0       | 1      | 2  |
|-----|-------------|------------- |----- |
| BP  |             |              |      |
| 0   | a00         | a01          | a02  |
| 1   | a10         | a11          | a12  |
| 2   | a20         | a21          |  a22 |


__Create a guess_matrix  for NaN values of *'Age'* ( using 'BMI' and 'BP')  and  *'glucoseLevel'*  (using 'BP' and 'Pedigree') for the given dataset and assign values accordingly to the NaNs in 'Age' or *'glucoseLevel'* .__


Refer to how we guessed age in the titanic notebook in the class.



In [206]:
guess_matrix_age= np.zeros((3,3),dtype=float) 
guess_matrix_age
guess_matrix_glucoseLevel= np.zeros((3,3),dtype=float) 
guess_matrix_glucoseLevel

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [207]:
# YOUR CODE HERE

# Fill the NA's for the Age columns
# with "qualified guesses"

for i in range(0, 3):
    for j in range(0,3):
        guess_df = data3[(data3['BMI'] == i)&(data3['BP'] == j)]['Age'].dropna()
        
        # Extract the median age for this group
        # (less sensitive) to outliers
        age_guess = guess_df.median()
        
        guess_matrix_age[i,j] = age_guess 

for i in range(0, 3):
    for j in range(0, 3):
        data3.loc[ (data3.Age.isnull()) & (data3.BMI == i) & (data3.BP == j),'Age'] = guess_matrix_age[i,j]

data3['Age'] = data3['Age']

print(guess_matrix_age)

[[24.5 25.  55.5]
 [29.5 29.  37. ]
 [33.  32.  31. ]]


In [208]:
for i in range(0, 3):
    for j in range(0,3):
        guess_df = data3[(data3['BP'] == i)&(data3['Pedigree'] == j)]['glucoseLevel'].dropna()
        
        # Extract the median age for this group
        # (less sensitive) to outliers
        glucoseLevel_guess = guess_df.median()
        
        # Convert random age float to int
        guess_matrix_glucoseLevel[i,j] = glucoseLevel_guess
        
guess_matrix_glucoseLevel

array([[115. , 127.5, 137. ],
       [112. , 115. , 149. ],
       [133. , 129. , 159.5]])

In [211]:
#guess_matrix_glucoseLevel == np.array([[115. , 127.5, 137. ],[112. , 115.5, 149. ],[133. , 129.5, 159.5]])

In [212]:
grader.check('q2f')

0 of 1 tests passed
    
    
    Tests failed: 
    
           ./tests\q2f.py

Test result:
Trying:
    guess_matrix_glucoseLevel
Expecting:
    array([[115. , 127.5, 137. ],
           [112. , 115.5, 149. ],
           [133. , 129.5, 159.5]])
**********************************************************************
Line 1, in ./tests\q2f.py 0
Failed example:
    guess_matrix_glucoseLevel
Expected:
    array([[115. , 127.5, 137. ],
           [112. , 115.5, 149. ],
           [133. , 129.5, 159.5]])
Got:
    array([[115. , 127.5, 137. ],
           [112. , 115. , 149. ],
           [133. , 129. , 159.5]])



__2.g Now, convert 'glucoseLevel' and 'Age' features also to categorical variables of 4 categories each in a dataframe called `data4`. PRINT the head of `data4`__








In [213]:
#Replace NaN's with estimated values
for i in range(0, 3):
    for j in range(0, 3):
        data3.loc[ (data3.Age.isnull()) & (data3.BMI == i) & (data3.BP == j),'Age'] = guess_matrix_age[i,j]

data3['Age'] = data3['Age']

for i in range(0, 3):
    for j in range(0, 3):
        data3.loc[ (data3.glucoseLevel.isnull()) & (data3.BP == i) & (data3.Pedigree == j),'glucoseLevel'] = guess_matrix_glucoseLevel[i,j]

data3['glucoseLevel'] = data3['glucoseLevel']

In [214]:
data3.isna().sum()

TimesPregnant    0
glucoseLevel     0
BP               0
insulin          0
BMI              0
Pedigree         0
Age              0
IsDiabetic       0
BMI_band         0
Pedigree_band    0
dtype: int64

In [215]:
# YOUR CODE HERE
data4 = data3.copy()
data4['glucoseLevel'] = pd.cut(data4['glucoseLevel'], bins = 4, labels = [0,1,2,3])
data4['Age'] = pd.cut(data4['Age'], bins = 4, labels = [0,1,2,3])
data4.head()

TimesPregnant glucoseLevel BP insulin BMI Pedigree Age  IsDiabetic  \
0              6            2  1       0   1        0   1           1   
1              1            2  1       0   1        0   0           0   
2              8            3  1       0   1        0   0           1   
3              1            2  1       0   1        0   0           0   
4              0            2  0       0   1        2   0           1   

           BMI_band    Pedigree_band  
0  (22.367, 44.733]  (0.0757, 0.859]  
1  (22.367, 44.733]  (0.0757, 0.859]  
2  (22.367, 44.733]  (0.0757, 0.859]  
3  (22.367, 44.733]  (0.0757, 0.859]  
4  (22.367, 44.733]    (1.639, 2.42]

In [216]:
data4.isna().sum()

TimesPregnant    0
glucoseLevel     0
BP               0
insulin          0
BMI              0
Pedigree         0
Age              0
IsDiabetic       0
BMI_band         0
Pedigree_band    0
dtype: int64

In [217]:
grader.check('q2g')

All tests passed!

__2.h Use this dataset (with all features in categorical form) to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies.__


In [218]:
numTest = round(0.15*len(data4),0)

train_df, test_df = data4.loc[numTest+1:,:], data4.loc[:numTest,:]
X_train = train_df.loc[:,'TimesPregnant':'Age']
Y_train = train_df.loc[:,'IsDiabetic']
X_test  = test_df.loc[:,'TimesPregnant':'Age']
Y_test= test_df.loc[:,'IsDiabetic']
X_train.shape, Y_train.shape, X_test.shape

((652, 7), (652,), (116, 7))

In [219]:
#Logistic Regression
logreg = LogisticRegression(solver = "newton-cg", multi_class = 'ovr')  # use newton-cg solver and 'ovr' for multi_class
logreg.fit(X_train, Y_train)
logreg_train_acc = logreg.score(X_train, Y_train)
logreg_test_acc = logreg.score(X_test, Y_test)
print ('logreg training acuracy= ',logreg_train_acc)
print('logreg test accuracy= ',logreg_test_acc)

logreg training acuracy=  0.7515337423312883
logreg test accuracy=  0.6896551724137931


In [42]:
# Perceptron
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
perceptron_train_acc = perceptron.score(X_train, Y_train)
perceptron_test_acc = perceptron.score(X_test, Y_test)
print ('perceptron training acuracy= ',perceptron_train_acc)
print('perceptron test accuracy= ',perceptron_test_acc)

perceptron training acuracy=  0.5352760736196319
perceptron test accuracy=  0.5172413793103449


In [43]:
# Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(X_train, Y_train)
random_forest_train_acc = random_forest.score(X_train, Y_train)
random_forest_test_acc = random_forest.score(X_test, Y_test)
print('random_forest training acuracy= ',random_forest_train_acc)
print('random_forest test accuracy= ',random_forest_test_acc)

C:\Users\Chad\.conda\envs\data-x\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


random_forest training acuracy=  0.8604294478527608
random_forest test accuracy=  0.75
